baseURL = 'https://opencut.dev'
languageCode = 'en-us'
title = 'OpenCut Documentation'
theme = 'hextra'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Documentation"
    pageRef = "/docs"
    weight = 10
  [[menu.main]]
    name = "Getting Started"
    pageRef = "/docs/getting-started"
    weight = 20
  [[menu.main]]
    name = "Development"
    pageRef = "/docs/development"
    weight = 30
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/OpenCut-app/OpenCut"
    weight = 40

[params]
  description = "A free, open-source video editor for web, desktop, and mobile"
  displayUpdatedDate = true
  DateFormat = "January 2, 2006"

  [params.navbar]
    displayTitle = true
    displayLogo = false

  [params.footer]
    displayCopyright = true
    displayPoweredBy = false

  [params.editPage]
    enable = false
